# Generated by Django 4.2.30 on 2026-08-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='genre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
