# Generated by Django 4.2.30 on 2026-08-11 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_homepage_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='certificate',
            field=models.CharField(default='U', max_length=10),
        ),
        migrations.AddField(
            model_name='homepage',
            name='date',
            field=models.DateField(default='2026-08-11'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='time',
            field=models.CharField(default=datetime.date(2026, 8, 11), max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homepage',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
