# Generated by Django 4.2.30 on 2026-08-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_homepage_certificate_homepage_date_homepage_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
