# Generated by Django 4.2.30 on 2026-08-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_homepage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='image2',
            field=models.ImageField(null=True, upload_to='homepage/'),
        ),
    ]
