# Generated by Django 4.2.30 on 2026-08-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_homepage_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='concert_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='language',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
