# Generated by Django 4.2.30 on 2026-08-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_homepage_concert_type_homepage_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hour',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='certificate',
            field=models.CharField(default='U', max_length=100),
        ),
    ]
