# Generated by Django 4.2.30 on 2026-08-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_homepage_hour_alter_homepage_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
