# Generated by Django 4.2.30 on 2026-08-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_homepage_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='moviefilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('language', models.CharField(max_length=100, null=True)),
                ('genre', models.CharField(max_length=100, null=True)),
                ('certificate', models.CharField(max_length=100, null=True)),
                ('format', models.CharField(max_length=100, null=True)),
                ('date', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(upload_to='homepage/')),
            ],
        ),
    ]
