# Generated by Django 4.2.30 on 2026-08-22 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_moviefilter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='moviefilter',
        ),
    ]
