# Generated by Django 4.2.30 on 2026-08-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_moviefilter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviefilter',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
