# Generated by Django 4.2.30 on 2026-08-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_moviefilter_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviefilter',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='moviefilter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/'),
        ),
    ]
