# Generated by Django 4.2.30 on 2026-08-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_moviefilter_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100, null=True)),
                ('language', models.CharField(max_length=100, null=True)),
                ('time', models.CharField(max_length=100, null=True)),
                ('genre', models.CharField(max_length=100, null=True)),
                ('certificate', models.CharField(max_length=100, null=True)),
                ('format', models.CharField(max_length=100, null=True)),
                ('date', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=100)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='homepage',
            name='default',
            field=models.CharField(default='Book ticket', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='format',
            field=models.CharField(default='2D, HDR By Barco, DOLBY CINEMA 2D, EPIQ', max_length=100),
        ),
    ]
