# Generated by Django 4.2.30 on 2026-08-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_streamingmovies_homepage_default_homepage_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviefilter',
            name='time',
            field=models.CharField(default='2h 30m', max_length=100),
        ),
    ]
