# Generated by Django 4.2.30 on 2026-08-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_moviefilter_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamingmovies',
            name='buy',
            field=models.CharField(default='Buy $89', max_length=100),
        ),
    ]
