# Generated by Django 4.2.30 on 2026-08-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_streamingmovies_buy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamingmovies',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
