# Generated by Django 4.2.30 on 2026-08-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_streamingmovies_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamingmovies',
            name='backgroundimage',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/'),
        ),
    ]
