# Generated by Django 4.2.30 on 2026-08-27 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_streamingmovies_backgroundimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streamingmovies',
            old_name='buy',
            new_name='default',
        ),
    ]
