# Generated by Django 4.2.30 on 2026-08-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_activitiesfilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviefilter',
            name='default',
            field=models.CharField(default='Book ticket', max_length=100),
        ),
    ]
