# Generated by Django 4.2.30 on 2026-09-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_theaterlist_showtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfilter',
            name='language',
            field=models.CharField(default='Tamil,English', max_length=100, null=True),
        ),
    ]
