# Generated by Django 4.2.30 on 2026-09-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_eventfilter_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='language',
            field=models.CharField(default='Tamil,English', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='moviefilter',
            name='language',
            field=models.CharField(default='Tamil,English', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='streamingmovies',
            name='language',
            field=models.CharField(default='Tamil,English', max_length=100, null=True),
        ),
    ]
