# Generated by Django 4.2.30 on 2026-09-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_homepage_language_alter_moviefilter_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamingmovies',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
