# Generated by Django 4.2.30 on 2026-09-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_streamingmovies_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamingmovies',
            name='default',
            field=models.CharField(default='Buy ₹89', max_length=100),
        ),
    ]
