# Generated by Django 4.2.30 on 2026-09-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_streamingmovies_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventfilter',
            name='concert_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventfilter',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
