# Generated by Django 4.2.30 on 2026-09-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_eventfilter_concert_type_eventfilter_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitiesfilter',
            name='concert_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activitiesfilter',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='playsfilter',
            name='concert_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='playsfilter',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sportfilter',
            name='concert_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sportfilter',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
